apiVersion: batch/v1
kind: Job
metadata:
    name: job
spec:
    schedule: "0,15,30,45 * * * *"
    jobTemplate:
        metadata:
            labels:
                app: job
        spec:
            completions: 5
            restartPolicy: onFailure
            containers:
                - name: batch-job
                  image: bahalla/batch-job