apiVersion: v1
kind: Pod
metadata:
    name: kubia2
    labels:
        app: kubia2
spec:
    containers:
        - image: bahalla/kubia2
          name: kubia2
          env:
            - name: ENV_VAR
              valueFrom: 
                configMapKeyRef:
                    name: app2-config
                    key: ENV_VAR